# Generated by Django 4.0 on 2024-05-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_movie_image'),
        ('booking', '0002_rename_user_user1'),
    ]

    operations = [
    ]
