# Generated by Django 3.2.2 on 2024-05-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_cinema_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
