# Generated by Django 3.2.2 on 2024-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_movie_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
