# Generated by Django 3.2.2 on 2024-05-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='end_time',
        ),
    ]
